- name: Use docker compose to run all containers
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: ./

    - name: Run docker compose up command
      docker_compose:
        project_src: ./
        state: present
        pull: yes
