---
- name: Run Docker Compose
  hosts: localhost
  connection: local
  tasks:
    - name: Run Docker Compose up command
      command: docker-compose up -d
      args:
        chdir: "{{ playbook_dir }}"
