server:
  port: 9093
spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: UserService
            uri: lb://UserService
            predicates:
              - Path=/api/customer/**,/auth/login

          - id: AccountService
            uri: lb://AccountService
            predicates:
              - Path=/api/accounts/**

          - id: NotificationService
            uri: lb://NotificationService
            predicates:
              - Path=/api/notifications/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
