spring:
  application:
    name: AccountService
  datasource:
    url: jdbc:mysql://localhost:3306/AccountServiceDatabase?createDatabaseIfNotExist=true
    username: root
    password: Start@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
