spring:
  application:
    name: NotificationService
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/NotificationServiceDatabase?createDatabaseIfNotExist=true}

    username: root
    password: Start@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
